# Derleyici
CXX = g++
# Derleme bayrakları
CXXFLAGS = -Wall -Wextra -std=c++17

# Hedef dosya (çıktı)
TARGET = program

# Kaynak dosyalar
SRCS = main.cpp fac.cpp

# Nesne dosyaları (otomatik türetilir)
OBJS = $(SRCS:.cpp=.o)

# Build süreci
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Temizleme komutu
clean:
	rm -f $(TARGET) $(OBJS)
